export const SHADOW_OUTLINE: string;
export const SHADOW_OUTLINE_2: string;
export const SHADOW_ERROR: string;
export const SHADOW_1: string;
export const SHADOW_2: string;
export const SHADOW_3: string;
export const SHADOW_4: string;
export const SHADOW_5: string;
export const SHADOW_6: string;
