const PageTable = require('../../../src/components/Table/pageObject');
const { SHIFT_KEY } = require('../../constants');
const holdDownKey = require('../../helpers/holdDownKey');
const releaseKey = require('../../helpers/releaseKey');

const TABLE = '#table-5';

describe('Table with selection', () => {
    beforeAll(() => {
        browser.url('/#!/Table/5');
    });
    beforeEach(() => {
        browser.refresh();
        const component = $(TABLE);
        component.waitForExist();
    });

    it('should select and then deselect a row', () => {
        const table = new PageTable(TABLE);
        table.waitUntilDataIsLoaded();
        const row5 = table.getRow(4);
        expect(row5.isRowSelected()).toBe(false);
        row5.selectRow();
        expect(row5.isRowSelected()).toBe(true);
        row5.deselectRow();
        expect(row5.isRowSelected()).toBe(false);
    });
    it('should select all rows', () => {
        const table = new PageTable(TABLE);
        table.waitUntilDataIsLoaded();
        const row1 = table.getRow(0);
        const row2 = table.getRow(1);
        const row3 = table.getRow(2);
        const row4 = table.getRow(3);
        const row5 = table.getRow(4);
        const row6 = table.getRow(5);
        const row7 = table.getRow(6);
        expect(row1.isRowSelected()).toBe(false);
        expect(row2.isRowSelected()).toBe(false);
        expect(row3.isRowSelected()).toBe(false);
        expect(row4.isRowSelected()).toBe(false);
        expect(row5.isRowSelected()).toBe(false);
        expect(row6.isRowSelected()).toBe(false);
        expect(row7.isRowSelected()).toBe(false);
        table.selectAllRows();
        expect(row1.isRowSelected()).toBe(true);
        expect(row2.isRowSelected()).toBe(true);
        expect(row3.isRowSelected()).toBe(true);
        expect(row4.isRowSelected()).toBe(true);
        expect(row5.isRowSelected()).toBe(true);
        expect(row6.isRowSelected()).toBe(true);
        expect(row7.isRowSelected()).toBe(true);
    });
    it('should deselect all rows', () => {
        const table = new PageTable(TABLE);
        table.waitUntilDataIsLoaded();
        const row1 = table.getRow(0);
        const row2 = table.getRow(1);
        const row3 = table.getRow(2);
        const row4 = table.getRow(3);
        const row5 = table.getRow(4);
        const row6 = table.getRow(5);
        const row7 = table.getRow(6);
        table.selectAllRows();
        table.deselectAllRows();
        expect(row1.isRowSelected()).toBe(false);
        expect(row2.isRowSelected()).toBe(false);
        expect(row3.isRowSelected()).toBe(false);
        expect(row4.isRowSelected()).toBe(false);
        expect(row5.isRowSelected()).toBe(false);
        expect(row6.isRowSelected()).toBe(false);
        expect(row7.isRowSelected()).toBe(false);
    });
    it('should select the second and fifth row', () => {
        const table = new PageTable(TABLE);
        table.waitUntilDataIsLoaded();
        const row1 = table.getRow(0);
        const row2 = table.getRow(1);
        const row3 = table.getRow(2);
        const row4 = table.getRow(3);
        const row5 = table.getRow(4);
        const row6 = table.getRow(5);
        const row7 = table.getRow(6);
        row2.selectRow();
        row5.selectRow();
        expect(row1.isRowSelected()).toBe(false);
        expect(row2.isRowSelected()).toBe(true);
        expect(row3.isRowSelected()).toBe(false);
        expect(row4.isRowSelected()).toBe(false);
        expect(row5.isRowSelected()).toBe(true);
        expect(row6.isRowSelected()).toBe(false);
        expect(row7.isRowSelected()).toBe(false);
    });
    it('should deselect all rows when the second and fifth row are selected and then deselect all rows', () => {
        const table = new PageTable(TABLE);
        table.waitUntilDataIsLoaded();
        const row1 = table.getRow(0);
        const row2 = table.getRow(1);
        const row3 = table.getRow(2);
        const row4 = table.getRow(3);
        const row5 = table.getRow(4);
        const row6 = table.getRow(5);
        const row7 = table.getRow(6);
        row2.selectRow();
        row5.selectRow();
        table.deselectAllRows();
        expect(row1.isRowSelected()).toBe(false);
        expect(row2.isRowSelected()).toBe(false);
        expect(row3.isRowSelected()).toBe(false);
        expect(row4.isRowSelected()).toBe(false);
        expect(row5.isRowSelected()).toBe(false);
        expect(row6.isRowSelected()).toBe(false);
        expect(row7.isRowSelected()).toBe(false);
    });
    it('should select all rows between selected rows while press shift key', () => {
        const table = new PageTable(TABLE);
        table.waitUntilDataIsLoaded();
        const row1 = table.getRow(0);
        const row2 = table.getRow(1);
        const row3 = table.getRow(2);
        const row4 = table.getRow(3);
        const row5 = table.getRow(4);
        const row6 = table.getRow(5);
        const row7 = table.getRow(6);
        row1.selectRow();
        holdDownKey(SHIFT_KEY);
        row5.selectRow();
        releaseKey(SHIFT_KEY);
        expect(row1.isRowSelected()).toBe(true);
        expect(row2.isRowSelected()).toBe(true);
        expect(row3.isRowSelected()).toBe(true);
        expect(row4.isRowSelected()).toBe(true);
        expect(row5.isRowSelected()).toBe(true);
        expect(row6.isRowSelected()).toBe(false);
        expect(row7.isRowSelected()).toBe(false);
    });
    it('should deselect all rows between the two rows deselected while press shift key', () => {
        const table = new PageTable(TABLE);
        table.waitUntilDataIsLoaded();
        const row1 = table.getRow(0);
        const row2 = table.getRow(1);
        const row3 = table.getRow(2);
        const row4 = table.getRow(3);
        const row5 = table.getRow(4);
        const row6 = table.getRow(5);
        const row7 = table.getRow(6);
        table.selectAllRows();
        row1.deselectRow();
        holdDownKey(SHIFT_KEY);
        row4.deselectRow();
        releaseKey(SHIFT_KEY);
        expect(row1.isRowSelected()).toBe(false);
        expect(row2.isRowSelected()).toBe(false);
        expect(row3.isRowSelected()).toBe(false);
        expect(row4.isRowSelected()).toBe(false);
        expect(row5.isRowSelected()).toBe(true);
        expect(row6.isRowSelected()).toBe(true);
        expect(row7.isRowSelected()).toBe(true);
    });
});
