module.exports = {
    TAB_KEY: 'Tab',
    ENTER_KEY: 'Enter',
    ESCAPE_KEY: 'Escape',
    SPACE_KEY: ' ',
    ARROW_LEFT_KEY: 'ArrowLeft',
    ARROW_UP_KEY: 'ArrowUp',
    ARROW_RIGHT_KEY: 'ArrowRight',
    ARROW_DOWN_KEY: 'ArrowDown',
    SHIFT_KEY: 'Shift',
    DELETE_KEY: 'Backspace',
    PAGEUP_KEY: 'PageUp',
    PAGEDOWN_KEY: 'PageDown',
    END_KEY: 'End',
    HOME_KEY: 'Home',
    ALT_KEY: 'Alt',
};
