module.exports = {
    TAB_KEY: 'Tab',
    ENTER_KEY: 'Enter',
    ESCAPE_KEY: 'Escape',
    SPACE_KEY: 'Space',
    ARROW_LEFT_KEY: 'ArrowLeft',
    ARROW_UP_KEY: 'ArrowUp',
    ARROW_RIGHT_KEY: 'ArrowRight',
    ARROW_DOWN_KEY: 'ArrowDown',
    SHIFT_KEY: 'Shift',
    DELETE_KEY: 'Delete',
    PAGEUP_KEY: 'PageUp',
    PAGEDOWN_KEY: 'PageDown',
    END_KEY: 'End',
    HOME_KEY: 'Home',
    ALT_KEY: 'Alt',
    BACKSPACE_KEY: 'Backspace',
    // Unicode key points
    SHIFT_KEY_UNICODE: '\uE008',
};
