import * as Flags from './flags';

export default [
    {
        flagIcon: Flags.Afghanistan,
        countryCode: '+93',
        country: 'Afghanistan',
        isoCode: 'af',
    },
    {
        flagIcon: Flags.AlandIslands,
        countryCode: '+358',
        country: 'Åland islands',
        isoCode: 'ax',
    },
    {
        flagIcon: Flags.Albania,
        countryCode: '+355',
        country: 'Albania',
        isoCode: 'al',
    },
    {
        flagIcon: Flags.Algeria,
        countryCode: '+213',
        country: 'Algeria',
        isoCode: 'dz',
    },
    {
        flagIcon: Flags.AmericanSamoa,
        countryCode: '+1',
        country: 'American Somoa',
        isoCode: 'as',
    },
    {
        flagIcon: Flags.Andorra,
        countryCode: '+376',
        country: 'Andorra',
        isoCode: 'ad',
    },
    {
        flagIcon: Flags.Angola,
        countryCode: '+244',
        country: 'Angola',
        isoCode: 'ao',
    },
    {
        flagIcon: Flags.Anguilla,
        countryCode: '+1',
        country: 'Anguilla',
        isoCode: 'ai',
    },
    {
        flagIcon: Flags.AntiguaAndBarbuda,
        countryCode: '+1',
        country: 'Antigua and Barbuda',
        isoCode: 'ag',
    },
    {
        flagIcon: Flags.Argentina,
        countryCode: '+54',
        country: 'Argentina',
        isoCode: 'ar',
    },
    {
        flagIcon: Flags.Armenia,
        countryCode: '+374',
        country: 'Armenia',
        isoCode: 'am',
    },
    {
        flagIcon: Flags.Aruba,
        countryCode: '+297',
        country: 'Aruba',
        isoCode: 'aw',
    },
    {
        flagIcon: Flags.AscensionIsland,
        countryCode: '+247',
        country: 'Ascension Island',
        isoCode: 'ac',
    },
    {
        flagIcon: Flags.Australia,
        countryCode: '+61',
        country: 'Australia',
        isoCode: 'au',
    },
    {
        flagIcon: Flags.Austria,
        countryCode: '+43',
        country: 'Austria',
        isoCode: 'at',
    },
    {
        flagIcon: Flags.Azerbaijan,
        countryCode: '+994',
        country: 'Azerbaijan',
        isoCode: 'az',
    },
    {
        flagIcon: Flags.Bahamas,
        countryCode: '+1',
        country: 'Bahamas',
        isoCode: 'bs',
    },
    {
        flagIcon: Flags.Bahrain,
        countryCode: '+973',
        country: 'Bahrain',
        isoCode: 'bh',
    },
    {
        flagIcon: Flags.Bangladesh,
        countryCode: '+880',
        country: 'Bangladesh',
        isoCode: 'bd',
    },
    {
        flagIcon: Flags.Barbados,
        countryCode: '+1',
        country: 'Barbados',
        isoCode: 'bb',
    },
    {
        flagIcon: Flags.Belarus,
        countryCode: '+375',
        country: 'Belarus',
        isoCode: 'by',
    },
    {
        flagIcon: Flags.Belgium,
        countryCode: '+32',
        country: 'Belgium',
        isoCode: 'be',
    },
    {
        flagIcon: Flags.Belize,
        countryCode: '+501',
        country: 'Belize',
        isoCode: 'bz',
    },
    {
        flagIcon: Flags.Benin,
        countryCode: '+229',
        country: 'Benin',
        isoCode: 'bj',
    },
    {
        flagIcon: Flags.Bermuda,
        countryCode: '+1',
        country: 'Bermuda',
        isoCode: 'bm',
    },
    {
        flagIcon: Flags.Bhutan,
        countryCode: '+975',
        country: 'Bhutan',
        isoCode: 'bt',
    },
    {
        flagIcon: Flags.Bolivia,
        countryCode: '+591',
        country: 'Bolivia',
        isoCode: 'bo',
    },
    {
        flagIcon: Flags.Bonaire,
        countryCode: '+599',
        country: 'Bonaire',
        isoCode: 'bq',
    },
    {
        flagIcon: Flags.BosniaAndHerzegovina,
        countryCode: '+387',
        country: 'Bosnia and Herzegovina',
        isoCode: 'ba',
    },
    {
        flagIcon: Flags.Botswana,
        countryCode: '+267',
        country: 'Botswana',
        isoCode: 'bw',
    },
    {
        flagIcon: Flags.Brazil,
        countryCode: '+55',
        country: 'Brazil',
        isoCode: 'br',
    },
    {
        flagIcon: Flags.BritishVirginIslands,
        countryCode: '+1',
        country: 'British Virgin Islands',
        isoCode: 'vg',
    },
    {
        flagIcon: Flags.Brunei,
        countryCode: '+673',
        country: 'Brunei',
        isoCode: 'bn',
    },
    {
        flagIcon: Flags.Bulgaria,
        countryCode: '+359',
        country: 'Bulgaria',
        isoCode: 'bg',
    },
    {
        flagIcon: Flags.BurkinaFaso,
        countryCode: '+226',
        country: 'Burkina Faso',
        isoCode: 'bf',
    },
    {
        flagIcon: Flags.Burundi,
        countryCode: '+257',
        country: 'Burundi',
        isoCode: 'bi',
    },
    {
        flagIcon: Flags.Cambodia,
        countryCode: '+855',
        country: 'Cambodia',
        isoCode: 'kh',
    },
    {
        flagIcon: Flags.Cameroon,
        countryCode: '+237',
        country: 'Cameroon',
        isoCode: 'cm',
    },
    {
        flagIcon: Flags.Canada,
        countryCode: '+1',
        country: 'Canada',
        isoCode: 'ca',
    },
    {
        flagIcon: Flags.CapeVerde,
        countryCode: '+238',
        country: 'Cape Verde',
        isoCode: 'cv',
    },
    {
        flagIcon: Flags.CaymanIslands,
        countryCode: '+1',
        country: 'Cayman Islands',
        isoCode: 'ky',
    },
    {
        flagIcon: Flags.CentralAfricanRepublic,
        countryCode: '+236',
        country: 'Central African Republic',
        isoCode: 'cf',
    },
    {
        flagIcon: Flags.Chad,
        countryCode: '+235',
        country: 'Chad',
        isoCode: 'td',
    },
    {
        flagIcon: Flags.Chile,
        countryCode: '+56',
        country: 'Chile',
        isoCode: 'cl',
    },
    {
        flagIcon: Flags.China,
        countryCode: '+86',
        country: 'China',
        isoCode: 'cn',
    },
    {
        flagIcon: Flags.ChristmasIsland,
        countryCode: '+61',
        country: 'Christmas Island',
        isoCode: 'cx',
    },
    {
        flagIcon: Flags.CocosIsland,
        countryCode: '+61',
        country: 'Cocos Island',
        isoCode: 'cc',
    },
    {
        flagIcon: Flags.Colombia,
        countryCode: '+57',
        country: 'Colombia',
        isoCode: 'co',
    },
    {
        flagIcon: Flags.Comoros,
        countryCode: '+269',
        country: 'Comoros',
        isoCode: 'km',
    },
    {
        flagIcon: Flags.CongoBrazzaville,
        countryCode: '+242',
        country: 'Congo - Brazzaville',
        isoCode: 'cg',
    },
    {
        flagIcon: Flags.CongoKinshasa,
        countryCode: '+243',
        country: 'Congo - Kinshasa',
        isoCode: 'cd',
    },
    {
        flagIcon: Flags.CookIslands,
        countryCode: '+682',
        country: 'Cook Islands',
        isoCode: 'ck',
    },
    {
        flagIcon: Flags.CostaRica,
        countryCode: '+506',
        country: 'Costa Rica',
        isoCode: 'cr',
    },
    {
        flagIcon: Flags.CoteDLvoire,
        countryCode: '+225',
        country: 'Côte d’lvoire',
        isoCode: 'ci',
    },
    {
        flagIcon: Flags.Croatia,
        countryCode: '+385',
        country: 'Croatia',
        isoCode: 'hr',
    },
    {
        flagIcon: Flags.Cuba,
        countryCode: '+53',
        country: 'Cuba',
        isoCode: 'cu',
    },
    {
        flagIcon: Flags.Curacao,
        countryCode: '+599',
        country: 'Curaçao',
        isoCode: 'cw',
    },
    {
        flagIcon: Flags.Cyprus,
        countryCode: '+357',
        country: 'Cyprus',
        isoCode: 'cy',
    },
    {
        flagIcon: Flags.CzechRepublic,
        countryCode: '+420',
        country: 'Czech Republic',
        isoCode: 'cz',
    },
    {
        flagIcon: Flags.Denmark,
        countryCode: '+45',
        country: 'Denmark',
        isoCode: 'dk',
    },
    {
        flagIcon: Flags.Djibouti,
        countryCode: '+253',
        country: 'Djibouti',
        isoCode: 'dj',
    },
    {
        flagIcon: Flags.Dominica,
        countryCode: '+1',
        country: 'Dominica',
        isoCode: 'dm',
    },
    {
        flagIcon: Flags.DominicanRepublic,
        countryCode: '+1',
        country: 'Dominican Republic',
        isoCode: 'do',
    },
    {
        flagIcon: Flags.Ecuador,
        countryCode: '+593',
        country: 'Ecuador',
        isoCode: 'ec',
    },
    {
        flagIcon: Flags.Egypt,
        countryCode: '+20',
        country: 'Egypt',
        isoCode: 'eg',
    },
    {
        flagIcon: Flags.ElSalvador,
        countryCode: '+503',
        country: 'El Salvador',
        isoCode: 'sv',
    },
    {
        flagIcon: Flags.EquatorialGuinea,
        countryCode: '+240',
        country: 'Equatorial Guinea',
        isoCode: 'gq',
    },
    {
        flagIcon: Flags.Eritrea,
        countryCode: '+291',
        country: 'Eritrea',
        isoCode: 'er',
    },
    {
        flagIcon: Flags.Estonia,
        countryCode: '+372',
        country: 'Estonia',
        isoCode: 'ee',
    },
    {
        flagIcon: Flags.Ethiopia,
        countryCode: '+251',
        country: 'Ethiopia',
        isoCode: 'et',
    },
    {
        flagIcon: Flags.FalklandIslands,
        countryCode: '+500',
        country: 'Falkland Islands',
        isoCode: 'fk',
    },
    {
        flagIcon: Flags.FaroeIslands,
        countryCode: '+298',
        country: 'Faroe Islands',
        isoCode: 'fo',
    },
    {
        flagIcon: Flags.Fiji,
        countryCode: '+679',
        country: 'Fiji',
        isoCode: 'fj',
    },
    {
        flagIcon: Flags.Finland,
        countryCode: '+358',
        country: 'Finland',
        isoCode: 'fi',
    },
    {
        flagIcon: Flags.France,
        countryCode: '+33',
        country: 'France',
        isoCode: 'fr',
    },
    {
        flagIcon: Flags.FrenchGuiana,
        countryCode: '+594',
        country: 'French Guiana',
        isoCode: 'gf',
    },
    {
        flagIcon: Flags.FrenchPolynesia,
        countryCode: '+689',
        country: 'French Polynesia',
        isoCode: 'pf',
    },
    {
        flagIcon: Flags.Gabon,
        countryCode: '+241',
        country: 'Gabon',
        isoCode: 'ga',
    },
    {
        flagIcon: Flags.Gambia,
        countryCode: '+220',
        country: 'Gambia',
        isoCode: 'gm',
    },
    {
        flagIcon: Flags.Georgia,
        countryCode: '+995',
        country: 'Georgia',
        isoCode: 'ge',
    },
    {
        flagIcon: Flags.Germany,
        countryCode: '+49',
        country: 'Germany',
        isoCode: 'de',
    },
    {
        flagIcon: Flags.Ghana,
        countryCode: '+233',
        country: 'Ghana',
        isoCode: 'gh',
    },
    {
        flagIcon: Flags.Gibraltar,
        countryCode: '+350',
        country: 'Gibraltar',
        isoCode: 'gi',
    },
    {
        flagIcon: Flags.Greece,
        countryCode: '+30',
        country: 'Greece',
        isoCode: 'gr',
    },
    {
        flagIcon: Flags.Greenland,
        countryCode: '+299',
        country: 'Greenland',
        isoCode: 'gl',
    },
    {
        flagIcon: Flags.Grenada,
        countryCode: '+1',
        country: 'Grenada',
        isoCode: 'gd',
    },
    {
        flagIcon: Flags.Guadeloupe,
        countryCode: '+590',
        country: 'Guadeloupe',
        isoCode: 'gp',
    },
    {
        flagIcon: Flags.Guam,
        countryCode: '+1',
        country: 'Guam',
        isoCode: 'gu',
    },
    {
        flagIcon: Flags.Guatemala,
        countryCode: '+502',
        country: 'Guatemala',
        isoCode: 'gt',
    },
    {
        flagIcon: Flags.Guernsey,
        countryCode: '+44',
        country: 'Guernsey',
        isoCode: 'gg',
    },
    {
        flagIcon: Flags.Guinea,
        countryCode: '+224',
        country: 'Guinea',
        isoCode: 'gn',
    },
    {
        flagIcon: Flags.GuineaBissau,
        countryCode: '+245',
        country: 'Guinea Bissau',
        isoCode: 'gw',
    },
    {
        flagIcon: Flags.Guyana,
        countryCode: '+592',
        country: 'Guyana',
        isoCode: 'gy',
    },
    {
        flagIcon: Flags.Haiti,
        countryCode: '+509',
        country: 'Haiti',
        isoCode: 'ht',
    },
    {
        flagIcon: Flags.Honduras,
        countryCode: '+504',
        country: 'Honduras',
        isoCode: 'hn',
    },
    {
        flagIcon: Flags.HongKongSarChina,
        countryCode: '+852',
        country: 'Hong Kong SAR China',
        isoCode: 'hk',
    },
    {
        flagIcon: Flags.Hungary,
        countryCode: '+36',
        country: 'Hungary',
        isoCode: 'hu',
    },
    {
        flagIcon: Flags.Iceland,
        countryCode: '+354',
        country: 'Iceland',
        isoCode: 'is',
    },
    {
        flagIcon: Flags.India,
        countryCode: '+91',
        country: 'India',
        isoCode: 'in',
    },
    {
        flagIcon: Flags.Indonesia,
        countryCode: '+62',
        country: 'Indonesia',
        isoCode: 'id',
    },
    {
        flagIcon: Flags.Iran,
        countryCode: '+98',
        country: 'Iran',
        isoCode: 'ir',
    },
    {
        flagIcon: Flags.Iraq,
        countryCode: '+964',
        country: 'Iraq',
        isoCode: 'iq',
    },
    {
        flagIcon: Flags.Ireland,
        countryCode: '+353',
        country: 'Ireland',
        isoCode: 'ie',
    },
    {
        flagIcon: Flags.IsleOfMan,
        countryCode: '+44',
        country: 'Isle of Man',
        isoCode: 'im',
    },
    {
        flagIcon: Flags.Israel,
        countryCode: '+972',
        country: 'Israel',
        isoCode: 'il',
    },
    {
        flagIcon: Flags.Italy,
        countryCode: '+39',
        country: 'Italy',
        isoCode: 'it',
    },
    {
        flagIcon: Flags.Jamaica,
        countryCode: '+1',
        country: 'Jamaica',
        isoCode: 'jm',
    },
    {
        flagIcon: Flags.Japan,
        countryCode: '+81',
        country: 'Japan',
        isoCode: 'jp',
    },
    {
        flagIcon: Flags.Jersey,
        countryCode: '+44',
        country: 'Jersey',
        isoCode: 'je',
    },
    {
        flagIcon: Flags.Jordan,
        countryCode: '+962',
        country: 'Jordan',
        isoCode: 'jo',
    },
    {
        flagIcon: Flags.Kazakhstan,
        countryCode: '+7',
        country: 'Kazakhstan',
        isoCode: 'kz',
    },
    {
        flagIcon: Flags.Kenya,
        countryCode: '+254',
        country: 'Kenya',
        isoCode: 'ke',
    },
    {
        flagIcon: Flags.Kiribati,
        countryCode: '+686',
        country: 'Kiribati',
        isoCode: 'ki',
    },
    {
        flagIcon: Flags.Kosovo,
        countryCode: '+383',
        country: 'Kosovo',
        isoCode: 'kv',
    },
    {
        flagIcon: Flags.Kuwait,
        countryCode: '+965',
        country: 'Kuwait',
        isoCode: 'kw',
    },
    {
        flagIcon: Flags.Kyrgyzstan,
        countryCode: '+996',
        country: 'Kyrgyzstan',
        isoCode: 'kg',
    },
    {
        flagIcon: Flags.Laos,
        countryCode: '+856',
        country: 'Laos',
        isoCode: 'la',
    },
    {
        flagIcon: Flags.Latvia,
        countryCode: '+371',
        country: 'Latvia',
        isoCode: 'lv',
    },
    {
        flagIcon: Flags.Lebanon,
        countryCode: '+961',
        country: 'Lebanon',
        isoCode: 'lb',
    },
    {
        flagIcon: Flags.Lesotho,
        countryCode: '+266',
        country: 'Lesotho',
        isoCode: 'ls',
    },
    {
        flagIcon: Flags.Liberia,
        countryCode: '+231',
        country: 'Liberia',
        isoCode: 'lr',
    },
    {
        flagIcon: Flags.Libya,
        countryCode: '+218',
        country: 'Libya',
        isoCode: 'ly',
    },
    {
        flagIcon: Flags.Liechtenstein,
        countryCode: '+423',
        country: 'Liechtenstein',
        isoCode: 'li',
    },
    {
        flagIcon: Flags.Lithuania,
        countryCode: '+370',
        country: 'Lithuania',
        isoCode: 'lt',
    },
    {
        flagIcon: Flags.Luxembourg,
        countryCode: '+352',
        country: 'Luxembourg',
        isoCode: 'lu',
    },
    {
        flagIcon: Flags.MacauSarChina,
        countryCode: '+853',
        country: 'Macau SAR China',
        isoCode: 'mo',
    },
    {
        flagIcon: Flags.Macedonia,
        countryCode: '+389',
        country: 'Macedonia',
        isoCode: 'mk',
    },
    {
        flagIcon: Flags.Madagascar,
        countryCode: '+261',
        country: 'Madagascar',
        isoCode: 'mg',
    },
    {
        flagIcon: Flags.Malawi,
        countryCode: '+265',
        country: 'Malawi',
        isoCode: 'mw',
    },
    {
        flagIcon: Flags.Malaysia,
        countryCode: '+60',
        country: 'Malaysia',
        isoCode: 'my',
    },
    {
        flagIcon: Flags.Maldives,
        countryCode: '+960',
        country: 'Maldives',
        isoCode: 'mv',
    },
    {
        flagIcon: Flags.Mali,
        countryCode: '+223',
        country: 'Mali',
        isoCode: 'ml',
    },
    {
        flagIcon: Flags.Malta,
        countryCode: '+356',
        country: 'Malta',
        isoCode: 'mt',
    },
    {
        flagIcon: Flags.MarshallIsland,
        countryCode: '+692',
        country: 'Marshall Islands',
        isoCode: 'mh',
    },
    {
        flagIcon: Flags.Martinique,
        countryCode: '+596',
        country: 'Martinique',
        isoCode: 'mq',
    },
    {
        flagIcon: Flags.Mauritania,
        countryCode: '+222',
        country: 'Mauritania',
        isoCode: 'mr',
    },
    {
        flagIcon: Flags.Mauritius,
        countryCode: '+230',
        country: 'Mauritius',
        isoCode: 'mu',
    },
    {
        flagIcon: Flags.Mayotte,
        countryCode: '+262',
        country: 'Mayotte',
        isoCode: 'yt',
    },
    {
        flagIcon: Flags.Mexico,
        countryCode: '+52',
        country: 'Mexico',
        isoCode: 'mx',
    },
    {
        flagIcon: Flags.Micronesia,
        countryCode: '+691',
        country: 'Micronesia',
        isoCode: 'fm',
    },
    {
        flagIcon: Flags.Moldova,
        countryCode: '+373',
        country: 'Moldova',
        isoCode: 'md',
    },
    {
        flagIcon: Flags.Monaco,
        countryCode: '+377',
        country: 'Monaco',
        isoCode: 'mc',
    },
    {
        flagIcon: Flags.Mongolia,
        countryCode: '+976',
        country: 'Mongolia',
        isoCode: 'mn',
    },
    {
        flagIcon: Flags.Montenegro,
        countryCode: '+382',
        country: 'Montenegro',
        isoCode: 'me',
    },
    {
        flagIcon: Flags.Montserrat,
        countryCode: '+1',
        country: 'Montserrat',
        isoCode: 'ms',
    },
    {
        flagIcon: Flags.Morocco,
        countryCode: '+212',
        country: 'Morocco',
        isoCode: 'ma',
    },
    {
        flagIcon: Flags.Mozambique,
        countryCode: '+258',
        country: 'Mozambique',
        isoCode: 'mz',
    },
    {
        flagIcon: Flags.Myanmar,
        countryCode: '+95',
        country: 'Myanmar',
        isoCode: 'mm',
    },
    {
        flagIcon: Flags.Namibia,
        countryCode: '+264',
        country: 'Namibia',
        isoCode: 'na',
    },
    {
        flagIcon: Flags.Nauru,
        countryCode: '+674',
        country: 'Nauru',
        isoCode: 'nr',
    },
    {
        flagIcon: Flags.Nepal,
        countryCode: '+977',
        country: 'Nepal',
        isoCode: 'np',
    },
    {
        flagIcon: Flags.Netherlands,
        countryCode: '+31',
        country: 'Netherlands',
        isoCode: 'nl',
    },
    {
        flagIcon: Flags.NewCaledonia,
        countryCode: '+687',
        country: 'New Caledonia',
        isoCode: 'nc',
    },
    {
        flagIcon: Flags.NewZealand,
        countryCode: '+64',
        country: 'New Zealand',
        isoCode: 'nz',
    },
    {
        flagIcon: Flags.Nicaragua,
        countryCode: '+505',
        country: 'Nicaragua',
        isoCode: 'ni',
    },
    {
        flagIcon: Flags.Niger,
        countryCode: '+227',
        country: 'Niger',
        isoCode: 'ne',
    },
    {
        flagIcon: Flags.Nigeria,
        countryCode: '+234',
        country: 'Nigeria',
        isoCode: 'ng',
    },
    {
        flagIcon: Flags.Niue,
        countryCode: '+683',
        country: 'Niue',
        isoCode: 'nu',
    },
    {
        flagIcon: Flags.NorfolkIsland,
        countryCode: '+672',
        country: 'Norfolk Island',
        isoCode: 'nf',
    },
    {
        flagIcon: Flags.NorthKorea,
        countryCode: '+850',
        country: 'North Korea',
        isoCode: 'kp',
    },
    {
        flagIcon: Flags.NorthernMarianasIslands,
        countryCode: '+1',
        country: 'Northern Mariana Islands',
        isoCode: 'mp',
    },
    {
        flagIcon: Flags.Norway,
        countryCode: '+47',
        country: 'Norway',
        isoCode: 'no',
    },
    {
        flagIcon: Flags.Oman,
        countryCode: '+968',
        country: 'Oman',
        isoCode: 'om',
    },
    {
        flagIcon: Flags.Pakistan,
        countryCode: '+92',
        country: 'Pakistan',
        isoCode: 'pk',
    },
    {
        flagIcon: Flags.Palau,
        countryCode: '+680',
        country: 'Palau',
        isoCode: 'pw',
    },
    {
        flagIcon: Flags.Palestine,
        countryCode: '+970',
        country: 'Palestine',
        isoCode: 'ps',
    },
    {
        flagIcon: Flags.Panama,
        countryCode: '+507',
        country: 'Panama',
        isoCode: 'pa',
    },
    {
        flagIcon: Flags.PapuaNewGuinea,
        countryCode: '+675',
        country: 'Papua New Guinea',
        isoCode: 'pg',
    },
    {
        flagIcon: Flags.Paraguay,
        countryCode: '+595',
        country: 'Paraguay',
        isoCode: 'py',
    },
    {
        flagIcon: Flags.Peru,
        countryCode: '+51',
        country: 'Peru',
        isoCode: 'pe',
    },
    {
        flagIcon: Flags.Philippines,
        countryCode: '+63',
        country: 'Philippines',
        isoCode: 'ph',
    },
    {
        flagIcon: Flags.Poland,
        countryCode: '+48',
        country: 'Poland',
        isoCode: 'pl',
    },
    {
        flagIcon: Flags.Portugal,
        countryCode: '+351',
        country: 'Portugal',
        isoCode: 'pt',
    },
    {
        flagIcon: Flags.PuertoRico,
        countryCode: '+1',
        country: 'Puerto Rico',
        isoCode: 'pr',
    },
    {
        flagIcon: Flags.Qatar,
        countryCode: '+974',
        country: 'Qatar',
        isoCode: 'qa',
    },
    {
        flagIcon: Flags.Reunion,
        countryCode: '+262',
        country: 'Réunion',
        isoCode: 're',
    },
    {
        flagIcon: Flags.Romania,
        countryCode: '+40',
        country: 'Romania',
        isoCode: 'ro',
    },
    {
        flagIcon: Flags.Russia,
        countryCode: '+7',
        country: 'Russia',
        isoCode: 'ru',
    },
    {
        flagIcon: Flags.Rwanda,
        countryCode: '+250',
        country: 'Rwanda',
        isoCode: 'rw',
    },
    {
        flagIcon: Flags.SaintBarthelemy,
        countryCode: '+590',
        country: 'Saint Barthélemy',
        isoCode: 'bl',
    },
    {
        flagIcon: Flags.SaintHelena,
        countryCode: '+290',
        country: 'Saint Helena',
        isoCode: 'sh',
    },
    {
        flagIcon: Flags.SaintKittsAndNevis,
        countryCode: '+1',
        country: 'Saint Kitts and Nevis',
        isoCode: 'kn',
    },
    {
        flagIcon: Flags.SaintLucia,
        countryCode: '+1',
        country: 'Saint Lucia',
        isoCode: 'lc',
    },
    {
        flagIcon: Flags.SaintMartin,
        countryCode: '+590',
        country: 'Saint Martin',
        isoCode: 'mf',
    },
    {
        flagIcon: Flags.SaintPierreAndMiquelon,
        countryCode: '+508',
        country: 'Saint Pierre and Miquelon',
        isoCode: 'pm',
    },
    {
        flagIcon: Flags.SaintVincentAndTheGrenadines,
        countryCode: '+1',
        country: 'Saint Vincent and the Grenadines',
        isoCode: 'vc',
    },
    {
        flagIcon: Flags.Samoa,
        countryCode: '+685',
        country: 'Samoa',
        isoCode: 'ws',
    },
    {
        flagIcon: Flags.SanMarino,
        countryCode: '+378',
        country: 'San Marino',
        isoCode: 'sm',
    },
    {
        flagIcon: Flags.SaoTomeAndPrince,
        countryCode: '+239',
        country: 'São Tomé and Príncipe',
        isoCode: 'st',
    },
    {
        flagIcon: Flags.SaudiArabia,
        countryCode: '+966',
        country: 'Saudi Arabia',
        isoCode: 'sa',
    },
    {
        flagIcon: Flags.Senegal,
        countryCode: '+221',
        country: 'Senegal',
        isoCode: 'sn',
    },
    {
        flagIcon: Flags.Serbia,
        countryCode: '+381',
        country: 'Serbia',
        isoCode: 'rs',
    },
    {
        flagIcon: Flags.Seychelles,
        countryCode: '+248',
        country: 'Seychelles',
        isoCode: 'sc',
    },
    {
        flagIcon: Flags.SierraLeone,
        countryCode: '+232',
        country: 'Sierra Leone',
        isoCode: 'sl',
    },
    {
        flagIcon: Flags.Singapore,
        countryCode: '+65',
        country: 'Singapore',
        isoCode: 'sg',
    },
    {
        flagIcon: Flags.SintMaarten,
        countryCode: '+1',
        country: 'Sint Maarten',
        isoCode: 'sx',
    },
    {
        flagIcon: Flags.Slovakia,
        countryCode: '+421',
        country: 'Slovakia',
        isoCode: 'sk',
    },
    {
        flagIcon: Flags.Slovenia,
        countryCode: '+386',
        country: 'Slovenia',
        isoCode: 'si',
    },
    {
        flagIcon: Flags.SolomonIslands,
        countryCode: '+677',
        country: 'Solomon Islands',
        isoCode: 'sb',
    },
    {
        flagIcon: Flags.Somalia,
        countryCode: '+252',
        country: 'Somalia',
        isoCode: 'so',
    },
    {
        flagIcon: Flags.SouthAfrica,
        countryCode: '+27',
        country: 'South Africa',
        isoCode: 'za',
    },
    {
        flagIcon: Flags.SouthKorea,
        countryCode: '+82',
        country: 'South Korea',
        isoCode: 'kr',
    },
    {
        flagIcon: Flags.SouthSudan,
        countryCode: '+211',
        country: 'South Sudan',
        isoCode: 'ss',
    },
    {
        flagIcon: Flags.Spain,
        countryCode: '+34',
        country: 'Spain',
        isoCode: 'es',
    },
    {
        flagIcon: Flags.SriLanka,
        countryCode: '+94',
        country: 'Sri Lanka',
        isoCode: 'lk',
    },
    {
        flagIcon: Flags.Sudan,
        countryCode: '+249',
        country: 'Sudan',
        isoCode: 'sd',
    },
    {
        flagIcon: Flags.Suriname,
        countryCode: '+597',
        country: 'Suriname',
        isoCode: 'sr',
    },
    {
        flagIcon: Flags.SvalbardAndJanMayen,
        countryCode: '+47',
        country: 'Svalbard and Jan Mayen',
        isoCode: 'sj',
    },
    {
        flagIcon: Flags.Swaziland,
        countryCode: '+268',
        country: 'Swaziland',
        isoCode: 'sz',
    },
    {
        flagIcon: Flags.Sweden,
        countryCode: '+46',
        country: 'Sweden',
        isoCode: 'se',
    },
    {
        flagIcon: Flags.Switzerland,
        countryCode: '+41',
        country: 'Switzerland',
        isoCode: 'ch',
    },
    {
        flagIcon: Flags.Syria,
        countryCode: '+963',
        country: 'Syria',
        isoCode: 'sy',
    },
    {
        flagIcon: Flags.Taiwan,
        countryCode: '+886',
        country: 'Taiwan',
        isoCode: 'tw',
    },
    {
        flagIcon: Flags.Tajikistan,
        countryCode: '+992',
        country: 'Tajikistan',
        isoCode: 'tj',
    },
    {
        flagIcon: Flags.Tanzania,
        countryCode: '+255',
        country: 'Tanzania',
        isoCode: 'tz',
    },
    {
        flagIcon: Flags.Thailand,
        countryCode: '+66',
        country: 'Thailand',
        isoCode: 'th',
    },
    {
        flagIcon: Flags.TimorLeste,
        countryCode: '+670',
        country: 'Timor-Leste',
        isoCode: 'tl',
    },
    {
        flagIcon: Flags.Togo,
        countryCode: '+228',
        country: 'Togo',
        isoCode: 'tg',
    },
    {
        flagIcon: Flags.Tokelau,
        countryCode: '+690',
        country: 'Tokelau',
        isoCode: 'tk',
    },
    {
        flagIcon: Flags.Tonga,
        countryCode: '+676',
        country: 'Tonga',
        isoCode: 'to',
    },
    {
        flagIcon: Flags.TrinidadAndTobago,
        countryCode: '+1',
        country: 'Trinidad and Tobago',
        isoCode: 'tt',
    },
    {
        flagIcon: Flags.Tunisia,
        countryCode: '+216',
        country: 'Tunisia',
        isoCode: 'tn',
    },
    {
        flagIcon: Flags.Turkey,
        countryCode: '+90',
        country: 'Turkey',
        isoCode: 'tr',
    },
    {
        flagIcon: Flags.Turkmenistan,
        countryCode: '+993',
        country: 'Turkmenistan',
        isoCode: 'tm',
    },
    {
        flagIcon: Flags.TurksAndCaicos,
        countryCode: '+1',
        country: 'Turks and Caicos Islands',
        isoCode: 'tc',
    },
    {
        flagIcon: Flags.Tuvalu,
        countryCode: '+688',
        country: 'Tuvalu',
        isoCode: 'tv',
    },
    {
        flagIcon: Flags.UsVirginIslands,
        countryCode: '+1',
        country: 'U.S Virgin Islands',
        isoCode: 'vi',
    },
    {
        flagIcon: Flags.Uganda,
        countryCode: '+256',
        country: 'Uganda',
        isoCode: 'ug',
    },
    {
        flagIcon: Flags.Ukraine,
        countryCode: '+380',
        country: 'Ukraine',
        isoCode: 'ua',
    },
    {
        flagIcon: Flags.UnitedArabEmirates,
        countryCode: '+971',
        country: 'United Arab Emirates',
        isoCode: 'ae',
    },
    {
        flagIcon: Flags.UnitedKingdom,
        countryCode: '+44',
        country: 'United Kingdom',
        isoCode: 'gb',
    },
    {
        flagIcon: Flags.UnitedStates,
        countryCode: '+1',
        country: 'United States',
        isoCode: 'us',
    },
    {
        flagIcon: Flags.Uruguay,
        countryCode: '+598',
        country: 'Uruguay',
        isoCode: 'uy',
    },
    {
        flagIcon: Flags.Uzbekistan,
        countryCode: '+998',
        country: 'Uzbekistan',
        isoCode: 'uz',
    },
    {
        flagIcon: Flags.Vanuatu,
        countryCode: '+678',
        country: 'Vanuatu',
        isoCode: 'vu',
    },
    {
        flagIcon: Flags.VaticanCity,
        countryCode: '+379',
        country: 'Vatican City',
        isoCode: 'va',
    },
    {
        flagIcon: Flags.Venezuela,
        countryCode: '+58',
        country: 'Venezuela',
        isoCode: 've',
    },
    {
        flagIcon: Flags.Vietnam,
        countryCode: '+84',
        country: 'Vietnam',
        isoCode: 'vn',
    },
    {
        flagIcon: Flags.WallisAndFutuna,
        countryCode: '+681',
        country: 'Wallis and Futuna',
        isoCode: 'wf',
    },
    {
        flagIcon: Flags.Yemen,
        countryCode: '+967',
        country: 'Yemen',
        isoCode: 'ye',
    },
    {
        flagIcon: Flags.Zambia,
        countryCode: '+260',
        country: 'Zambia',
        isoCode: 'zm',
    },
    {
        flagIcon: Flags.Zimbabwe,
        countryCode: '+263',
        country: 'Zimbabwe',
        isoCode: 'zw',
    },
];
