/* eslintDisable global-require */
import React from 'react';
import * as Flags from './flags';

const style = {
    width: '28px',
    height: '28px',
    verticalAlign: 'middle',
};
export default [
    {
        flagIcon: <Flags.Afghanistan style={style} />,
        countryCode: '+93',
        country: 'Afghanistan',
        isoCode: 'af',
    },
    {
        flagIcon: <Flags.AlandIslands style={style} />,
        countryCode: '+358',
        country: 'Åland islands',
        isoCode: 'ax',
    },
    {
        flagIcon: <Flags.Albania style={style} />,
        countryCode: '+355',
        country: 'Albania',
        isoCode: 'al',
    },
    {
        flagIcon: <Flags.Algeria style={style} />,
        countryCode: '+213',
        country: 'Algeria',
        isoCode: 'dz',
    },
    {
        flagIcon: <Flags.AmericanSamoa style={style} />,
        countryCode: '+1',
        country: 'American Somoa',
        isoCode: 'as',
    },
    {
        flagIcon: <Flags.Andorra style={style} />,
        countryCode: '+376',
        country: 'Andorra',
        isoCode: 'ad',
    },
    {
        flagIcon: <Flags.Angola style={style} />,
        countryCode: '+244',
        country: 'Angola',
        isoCode: 'ao',
    },
    {
        flagIcon: <Flags.Anguilla style={style} />,
        countryCode: '+1',
        country: 'Anguilla',
        isoCode: 'ai',
    },
    {
        flagIcon: <Flags.AntiguaAndBarbuda style={style} />,
        countryCode: '+1',
        country: 'Antigua and Barbuda',
        isoCode: 'ag',
    },
    {
        flagIcon: <Flags.Argentina style={style} />,
        countryCode: '+54',
        country: 'Argentina',
        isoCode: 'ar',
    },
    {
        flagIcon: <Flags.Armenia style={style} />,
        countryCode: '+374',
        country: 'Armenia',
        isoCode: 'am',
    },
    {
        flagIcon: <Flags.Aruba style={style} />,
        countryCode: '+297',
        country: 'Aruba',
        isoCode: 'aw',
    },
    {
        flagIcon: <Flags.AscensionIsland style={style} />,
        countryCode: '+247',
        country: 'Ascension Island',
        isoCode: 'ac',
    },
    {
        flagIcon: <Flags.Australia style={style} />,
        countryCode: '+61',
        country: 'Australia',
        isoCode: 'au',
    },
    {
        flagIcon: <Flags.Austria style={style} />,
        countryCode: '+43',
        country: 'Austria',
        isoCode: 'at',
    },
    {
        flagIcon: <Flags.Azerbaijan style={style} />,
        countryCode: '+994',
        country: 'Azerbaijan',
        isoCode: 'az',
    },
    {
        flagIcon: <Flags.Bahamas style={style} />,
        countryCode: '+1',
        country: 'Bahamas',
        isoCode: 'bs',
    },
    {
        flagIcon: <Flags.Bahrain style={style} />,
        countryCode: '+973',
        country: 'Bahrain',
        isoCode: 'bh',
    },
    {
        flagIcon: <Flags.Bangladesh style={style} />,
        countryCode: '+880',
        country: 'Bangladesh',
        isoCode: 'bd',
    },
    {
        flagIcon: <Flags.Barbados style={style} />,
        countryCode: '+1',
        country: 'Barbados',
        isoCode: 'bb',
    },
    {
        flagIcon: <Flags.Belarus style={style} />,
        countryCode: '+375',
        country: 'Belarus',
        isoCode: 'by',
    },
    {
        flagIcon: <Flags.Belgium style={style} />,
        countryCode: '+32',
        country: 'Belgium',
        isoCode: 'be',
    },
    {
        flagIcon: <Flags.Belize style={style} />,
        countryCode: '+501',
        country: 'Belize',
        isoCode: 'bz',
    },
    {
        flagIcon: <Flags.Benin style={style} />,
        countryCode: '+229',
        country: 'Benin',
        isoCode: 'bj',
    },
    {
        flagIcon: <Flags.Bermuda style={style} />,
        countryCode: '+1',
        country: 'Bermuda',
        isoCode: 'bm',
    },
    {
        flagIcon: <Flags.Bhutan style={style} />,
        countryCode: '+975',
        country: 'Bhutan',
        isoCode: 'bt',
    },
    {
        flagIcon: <Flags.Bolivia style={style} />,
        countryCode: '+591',
        country: 'Bolivia',
        isoCode: 'bo',
    },
    {
        flagIcon: <Flags.Bonaire style={style} />,
        countryCode: '+599',
        country: 'Bonaire',
        isoCode: 'bq',
    },
    {
        flagIcon: <Flags.BosniaAndHerzegovina style={style} />,
        countryCode: '+387',
        country: 'Bosnia and Herzegovina',
        isoCode: 'ba',
    },
    {
        flagIcon: <Flags.Botswana style={style} />,
        countryCode: '+267',
        country: 'Botswana',
        isoCode: 'bw',
    },
    {
        flagIcon: <Flags.Brazil style={style} />,
        countryCode: '+55',
        country: 'Brazil',
        isoCode: 'br',
    },
    {
        flagIcon: <Flags.BritishVirginIslands style={style} />,
        countryCode: '+1',
        country: 'British Virgin Islands',
        isoCode: 'vg',
    },
    {
        flagIcon: <Flags.Brunei style={style} />,
        countryCode: '+673',
        country: 'Brunei',
        isoCode: 'bn',
    },
    {
        flagIcon: <Flags.Bulgaria style={style} />,
        countryCode: '+359',
        country: 'Bulgaria',
        isoCode: 'bg',
    },
    {
        flagIcon: <Flags.BurkinaFaso style={style} />,
        countryCode: '+226',
        country: 'Burkina Faso',
        isoCode: 'bf',
    },
    {
        flagIcon: <Flags.Burundi style={style} />,
        countryCode: '+257',
        country: 'Burundi',
        isoCode: 'bi',
    },
    {
        flagIcon: <Flags.Cambodia style={style} />,
        countryCode: '+855',
        country: 'Cambodia',
        isoCode: 'kh',
    },
    {
        flagIcon: <Flags.Cameroon style={style} />,
        countryCode: '+237',
        country: 'Cameroon',
        isoCode: 'cm',
    },
    {
        flagIcon: <Flags.Canada style={style} />,
        countryCode: '+1',
        country: 'Canada',
        isoCode: 'ca',
    },
    {
        flagIcon: <Flags.CapeVerde style={style} />,
        countryCode: '+238',
        country: 'Cape Verde',
        isoCode: 'cv',
    },
    {
        flagIcon: <Flags.CaymanIslands style={style} />,
        countryCode: '+1',
        country: 'Cayman Islands',
        isoCode: 'ky',
    },
    {
        flagIcon: <Flags.CentralAfricanRepublic style={style} />,
        countryCode: '+236',
        country: 'Central African Republic',
        isoCode: 'cf',
    },
    {
        flagIcon: <Flags.Chad style={style} />,
        countryCode: '+235',
        country: 'Chad',
        isoCode: 'td',
    },
    {
        flagIcon: <Flags.Chile style={style} />,
        countryCode: '+56',
        country: 'Chile',
        isoCode: 'cl',
    },
    {
        flagIcon: <Flags.China style={style} />,
        countryCode: '+86',
        country: 'China',
        isoCode: 'cn',
    },
    {
        flagIcon: <Flags.ChristmasIsland style={style} />,
        countryCode: '+61',
        country: 'Christmas Island',
        isoCode: 'cx',
    },
    {
        flagIcon: <Flags.CocosIsland style={style} />,
        countryCode: '+61',
        country: 'Cocos Island',
        isoCode: 'cc',
    },
    {
        flagIcon: <Flags.Colombia style={style} />,
        countryCode: '+57',
        country: 'Colombia',
        isoCode: 'co',
    },
    {
        flagIcon: <Flags.Comoros style={style} />,
        countryCode: '+269',
        country: 'Comoros',
        isoCode: 'km',
    },
    {
        flagIcon: <Flags.CongoBrazzaville style={style} />,
        countryCode: '+242',
        country: 'Congo - Brazzaville',
        isoCode: 'cg',
    },
    {
        flagIcon: <Flags.CongoKinshasa style={style} />,
        countryCode: '+243',
        country: 'Congo - Kinshasa',
        isoCode: 'cd',
    },
    {
        flagIcon: <Flags.CookIslands style={style} />,
        countryCode: '+682',
        country: 'Cook Islands',
        isoCode: 'ck',
    },
    {
        flagIcon: <Flags.CostaRica style={style} />,
        countryCode: '+506',
        country: 'Costa Rica',
        isoCode: 'cr',
    },
    {
        flagIcon: <Flags.CoteDLvoire style={style} />,
        countryCode: '+225',
        country: 'Côte d’lvoire',
        isoCode: 'ci',
    },
    {
        flagIcon: <Flags.Croatia style={style} />,
        countryCode: '+385',
        country: 'Croatia',
        isoCode: 'hr',
    },
    {
        flagIcon: <Flags.Cuba style={style} />,
        countryCode: '+53',
        country: 'Cuba',
        isoCode: 'cu',
    },
    {
        flagIcon: <Flags.Curacao style={style} />,
        countryCode: '+599',
        country: 'Curaçao',
        isoCode: 'cw',
    },
    {
        flagIcon: <Flags.Cyprus style={style} />,
        countryCode: '+357',
        country: 'Cyprus',
        isoCode: 'cy',
    },
    {
        flagIcon: <Flags.CzechRepublic style={style} />,
        countryCode: '+420',
        country: 'Czech Republic',
        isoCode: 'cz',
    },
    {
        flagIcon: <Flags.Denmark style={style} />,
        countryCode: '+45',
        country: 'Denmark',
        isoCode: 'dk',
    },
    {
        flagIcon: <Flags.Djibouti style={style} />,
        countryCode: '+253',
        country: 'Djibouti',
        isoCode: 'dj',
    },
    {
        flagIcon: <Flags.Dominica style={style} />,
        countryCode: '+1',
        country: 'Dominica',
        isoCode: 'dm',
    },
    {
        flagIcon: <Flags.DominicanRepublic style={style} />,
        countryCode: '+1',
        country: 'Dominican Republic',
        isoCode: 'do',
    },
    {
        flagIcon: <Flags.Ecuador style={style} />,
        countryCode: '+593',
        country: 'Ecuador',
        isoCode: 'ec',
    },
    {
        flagIcon: <Flags.Egypt style={style} />,
        countryCode: '+20',
        country: 'Egypt',
        isoCode: 'eg',
    },
    {
        flagIcon: <Flags.ElSalvador style={style} />,
        countryCode: '+503',
        country: 'El Salvador',
        isoCode: 'sv',
    },
    {
        flagIcon: <Flags.EquatorialGuinea style={style} />,
        countryCode: '+240',
        country: 'Equatorial Guinea',
        isoCode: 'gq',
    },
    {
        flagIcon: <Flags.Eritrea style={style} />,
        countryCode: '+291',
        country: 'Eritrea',
        isoCode: 'er',
    },
    {
        flagIcon: <Flags.Estonia style={style} />,
        countryCode: '+372',
        country: 'Estonia',
        isoCode: 'ee',
    },
    {
        flagIcon: <Flags.Ethiopia style={style} />,
        countryCode: '+251',
        country: 'Ethiopia',
        isoCode: 'et',
    },
    {
        flagIcon: <Flags.FalklandIslands style={style} />,
        countryCode: '+500',
        country: 'Falkland Islands',
        isoCode: 'fk',
    },
    {
        flagIcon: <Flags.FaroeIslands style={style} />,
        countryCode: '+298',
        country: 'Faroe Islands',
        isoCode: 'fo',
    },
    {
        flagIcon: <Flags.Fiji style={style} />,
        countryCode: '+679',
        country: 'Fiji',
        isoCode: 'fj',
    },
    {
        flagIcon: <Flags.Finland style={style} />,
        countryCode: '+358',
        country: 'Finland',
        isoCode: 'fi',
    },
    {
        flagIcon: <Flags.France style={style} />,
        countryCode: '+33',
        country: 'France',
        isoCode: 'fr',
    },
    {
        flagIcon: <Flags.FrenchGuiana style={style} />,
        countryCode: '+594',
        country: 'French Guiana',
        isoCode: 'gf',
    },
    {
        flagIcon: <Flags.FrenchPolynesia style={style} />,
        countryCode: '+689',
        country: 'French Polynesia',
        isoCode: 'pf',
    },
    {
        flagIcon: <Flags.Gabon style={style} />,
        countryCode: '+241',
        country: 'Gabon',
        isoCode: 'ga',
    },
    {
        flagIcon: <Flags.Gambia style={style} />,
        countryCode: '+220',
        country: 'Gambia',
        isoCode: 'gm',
    },
    {
        flagIcon: <Flags.Georgia style={style} />,
        countryCode: '+995',
        country: 'Georgia',
        isoCode: 'ge',
    },
    {
        flagIcon: <Flags.Germany style={style} />,
        countryCode: '+49',
        country: 'Germany',
        isoCode: 'de',
    },
    {
        flagIcon: <Flags.Ghana style={style} />,
        countryCode: '+233',
        country: 'Ghana',
        isoCode: 'gh',
    },
    {
        flagIcon: <Flags.Gibraltar style={style} />,
        countryCode: '+350',
        country: 'Gibraltar',
        isoCode: 'gi',
    },
    {
        flagIcon: <Flags.Greece style={style} />,
        countryCode: '+30',
        country: 'Greece',
        isoCode: 'gr',
    },
    {
        flagIcon: <Flags.Greenland style={style} />,
        countryCode: '+299',
        country: 'Greenland',
        isoCode: 'gl',
    },
    {
        flagIcon: <Flags.Grenada style={style} />,
        countryCode: '+1',
        country: 'Grenada',
        isoCode: 'gd',
    },
    {
        flagIcon: <Flags.Guadeloupe style={style} />,
        countryCode: '+590',
        country: 'Guadeloupe',
        isoCode: 'gp',
    },
    {
        flagIcon: <Flags.Guam style={style} />,
        countryCode: '+1',
        country: 'Guam',
        isoCode: 'gu',
    },
    {
        flagIcon: <Flags.Guatemala style={style} />,
        countryCode: '+502',
        country: 'Guatemala',
        isoCode: 'gt',
    },
    {
        flagIcon: <Flags.Guernsey style={style} />,
        countryCode: '+44',
        country: 'Guernsey',
        isoCode: 'gg',
    },
    {
        flagIcon: <Flags.Guinea style={style} />,
        countryCode: '+224',
        country: 'Guinea',
        isoCode: 'gn',
    },
    {
        flagIcon: <Flags.GuineaBissau style={style} />,
        countryCode: '+245',
        country: 'Guinea Bissau',
        isoCode: 'gw',
    },
    {
        flagIcon: <Flags.Guyana style={style} />,
        countryCode: '+592',
        country: 'Guyana',
        isoCode: 'gy',
    },
    {
        flagIcon: <Flags.Haiti style={style} />,
        countryCode: '+509',
        country: 'Haiti',
        isoCode: 'ht',
    },
    {
        flagIcon: <Flags.Honduras style={style} />,
        countryCode: '+504',
        country: 'Honduras',
        isoCode: 'hn',
    },
    {
        flagIcon: <Flags.HongKongSarChina style={style} />,
        countryCode: '+852',
        country: 'Hong Kong SAR China',
        isoCode: 'hk',
    },
    {
        flagIcon: <Flags.Hungary style={style} />,
        countryCode: '+36',
        country: 'Hungary',
        isoCode: 'hu',
    },
    {
        flagIcon: <Flags.Iceland style={style} />,
        countryCode: '+354',
        country: 'Iceland',
        isoCode: 'is',
    },
    {
        flagIcon: <Flags.India style={style} />,
        countryCode: '+91',
        country: 'India',
        isoCode: 'in',
    },
    {
        flagIcon: <Flags.Indonesia style={style} />,
        countryCode: '+62',
        country: 'Indonesia',
        isoCode: 'id',
    },
    {
        flagIcon: <Flags.Iran style={style} />,
        countryCode: '+98',
        country: 'Iran',
        isoCode: 'ir',
    },
    {
        flagIcon: <Flags.Iraq style={style} />,
        countryCode: '+964',
        country: 'Iraq',
        isoCode: 'iq',
    },
    {
        flagIcon: <Flags.Ireland style={style} />,
        countryCode: '+353',
        country: 'Ireland',
        isoCode: 'ie',
    },
    {
        flagIcon: <Flags.IsleOfMan style={style} />,
        countryCode: '+44',
        country: 'Isle of Man',
        isoCode: 'im',
    },
    {
        flagIcon: <Flags.Israel style={style} />,
        countryCode: '+972',
        country: 'Israel',
        isoCode: 'il',
    },
    {
        flagIcon: <Flags.Italy style={style} />,
        countryCode: '+39',
        country: 'Italy',
        isoCode: 'it',
    },
    {
        flagIcon: <Flags.Jamaica style={style} />,
        countryCode: '+1',
        country: 'Jamaica',
        isoCode: 'jm',
    },
    {
        flagIcon: <Flags.Japan style={style} />,
        countryCode: '+81',
        country: 'Japan',
        isoCode: 'jp',
    },
    {
        flagIcon: <Flags.Jersey style={style} />,
        countryCode: '+44',
        country: 'Jersey',
        isoCode: 'je',
    },
    {
        flagIcon: <Flags.Jordan style={style} />,
        countryCode: '+962',
        country: 'Jordan',
        isoCode: 'jo',
    },
    {
        flagIcon: <Flags.Kazakhstan style={style} />,
        countryCode: '+7',
        country: 'Kazakhstan',
        isoCode: 'kz',
    },
    {
        flagIcon: <Flags.Kenya style={style} />,
        countryCode: '+254',
        country: 'Kenya',
        isoCode: 'ke',
    },
    {
        flagIcon: <Flags.Kiribati style={style} />,
        countryCode: '+686',
        country: 'Kiribati',
        isoCode: 'ki',
    },
    {
        flagIcon: <Flags.Kosovo style={style} />,
        countryCode: '+383',
        country: 'Kosovo',
        isoCode: 'kv',
    },
    {
        flagIcon: <Flags.Kuwait style={style} />,
        countryCode: '+965',
        country: 'Kuwait',
        isoCode: 'kw',
    },
    {
        flagIcon: <Flags.Kyrgyzstan style={style} />,
        countryCode: '+996',
        country: 'Kyrgyzstan',
        isoCode: 'kg',
    },
    {
        flagIcon: <Flags.Laos style={style} />,
        countryCode: '+856',
        country: 'Laos',
        isoCode: 'la',
    },
    {
        flagIcon: <Flags.Latvia style={style} />,
        countryCode: '+371',
        country: 'Latvia',
        isoCode: 'lv',
    },
    {
        flagIcon: <Flags.Lebanon style={style} />,
        countryCode: '+961',
        country: 'Lebanon',
        isoCode: 'lb',
    },
    {
        flagIcon: <Flags.Lesotho style={style} />,
        countryCode: '+266',
        country: 'Lesotho',
        isoCode: 'ls',
    },
    {
        flagIcon: <Flags.Liberia style={style} />,
        countryCode: '+231',
        country: 'Liberia',
        isoCode: 'lr',
    },
    {
        flagIcon: <Flags.Libya style={style} />,
        countryCode: '+218',
        country: 'Libya',
        isoCode: 'ly',
    },
    {
        flagIcon: <Flags.Liechtenstein style={style} />,
        countryCode: '+423',
        country: 'Liechtenstein',
        isoCode: 'li',
    },
    {
        flagIcon: <Flags.Lithuania style={style} />,
        countryCode: '+370',
        country: 'Lithuania',
        isoCode: 'lt',
    },
    {
        flagIcon: <Flags.Luxembourg style={style} />,
        countryCode: '+352',
        country: 'Luxembourg',
        isoCode: 'lu',
    },
    {
        flagIcon: <Flags.MacauSarChina style={style} />,
        countryCode: '+853',
        country: 'Macau SAR China',
        isoCode: 'mo',
    },
    {
        flagIcon: <Flags.Macedonia style={style} />,
        countryCode: '+389',
        country: 'Macedonia',
        isoCode: 'mk',
    },
    {
        flagIcon: <Flags.Madagascar style={style} />,
        countryCode: '+261',
        country: 'Madagascar',
        isoCode: 'mg',
    },
    {
        flagIcon: <Flags.Malawi style={style} />,
        countryCode: '+265',
        country: 'Malawi',
        isoCode: 'mw',
    },
    {
        flagIcon: <Flags.Malaysia style={style} />,
        countryCode: '+60',
        country: 'Malaysia',
        isoCode: 'my',
    },
    {
        flagIcon: <Flags.Maldives style={style} />,
        countryCode: '+960',
        country: 'Maldives',
        isoCode: 'mv',
    },
    {
        flagIcon: <Flags.Mali style={style} />,
        countryCode: '+223',
        country: 'Mali',
        isoCode: 'ml',
    },
    {
        flagIcon: <Flags.Malta style={style} />,
        countryCode: '+356',
        country: 'Malta',
        isoCode: 'mt',
    },
    {
        flagIcon: <Flags.MarshallIsland style={style} />,
        countryCode: '+692',
        country: 'Marshall Islands',
        isoCode: 'mh',
    },
    {
        flagIcon: <Flags.Martinique style={style} />,
        countryCode: '+596',
        country: 'Martinique',
        isoCode: 'mq',
    },
    {
        flagIcon: <Flags.Mauritania style={style} />,
        countryCode: '+222',
        country: 'Mauritania',
        isoCode: 'mr',
    },
    {
        flagIcon: <Flags.Mauritius style={style} />,
        countryCode: '+230',
        country: 'Mauritius',
        isoCode: 'mu',
    },
    {
        flagIcon: <Flags.Mayotte style={style} />,
        countryCode: '+262',
        country: 'Mayotte',
        isoCode: 'yt',
    },
    {
        flagIcon: <Flags.Mexico style={style} />,
        countryCode: '+52',
        country: 'Mexico',
        isoCode: 'mx',
    },
    {
        flagIcon: <Flags.Micronesia style={style} />,
        countryCode: '+691',
        country: 'Micronesia',
        isoCode: 'fm',
    },
    {
        flagIcon: <Flags.Moldova style={style} />,
        countryCode: '+373',
        country: 'Moldova',
        isoCode: 'md',
    },
    {
        flagIcon: <Flags.Monaco style={style} />,
        countryCode: '+377',
        country: 'Monaco',
        isoCode: 'mc',
    },
    {
        flagIcon: <Flags.Mongolia style={style} />,
        countryCode: '+976',
        country: 'Mongolia',
        isoCode: 'mn',
    },
    {
        flagIcon: <Flags.Montenegro style={style} />,
        countryCode: '+382',
        country: 'Montenegro',
        isoCode: 'me',
    },
    {
        flagIcon: <Flags.Montserrat style={style} />,
        countryCode: '+1',
        country: 'Montserrat',
        isoCode: 'ms',
    },
    {
        flagIcon: <Flags.Morocco style={style} />,
        countryCode: '+212',
        country: 'Morocco',
        isoCode: 'ma',
    },
    {
        flagIcon: <Flags.Mozambique style={style} />,
        countryCode: '+258',
        country: 'Mozambique',
        isoCode: 'mz',
    },
    {
        flagIcon: <Flags.Myanmar style={style} />,
        countryCode: '+95',
        country: 'Myanmar',
        isoCode: 'mm',
    },
    {
        flagIcon: <Flags.Namibia style={style} />,
        countryCode: '+264',
        country: 'Namibia',
        isoCode: 'na',
    },
    {
        flagIcon: <Flags.Nauru style={style} />,
        countryCode: '+674',
        country: 'Nauru',
        isoCode: 'nr',
    },
    {
        flagIcon: <Flags.Nepal style={style} />,
        countryCode: '+977',
        country: 'Nepal',
        isoCode: 'np',
    },
    {
        flagIcon: <Flags.Netherlands style={style} />,
        countryCode: '+31',
        country: 'Netherlands',
        isoCode: 'nl',
    },
    {
        flagIcon: <Flags.NewCaledonia style={style} />,
        countryCode: '+687',
        country: 'New Caledonia',
        isoCode: 'nc',
    },
    {
        flagIcon: <Flags.NewZealand style={style} />,
        countryCode: '+64',
        country: 'New Zealand',
        isoCode: 'nz',
    },
    {
        flagIcon: <Flags.Nicaragua style={style} />,
        countryCode: '+505',
        country: 'Nicaragua',
        isoCode: 'ni',
    },
    {
        flagIcon: <Flags.Niger style={style} />,
        countryCode: '+227',
        country: 'Niger',
        isoCode: 'ne',
    },
    {
        flagIcon: <Flags.Nigeria style={style} />,
        countryCode: '+234',
        country: 'Nigeria',
        isoCode: 'ng',
    },
    {
        flagIcon: <Flags.Niue style={style} />,
        countryCode: '+683',
        country: 'Niue',
        isoCode: 'nu',
    },
    {
        flagIcon: <Flags.NorfolkIsland style={style} />,
        countryCode: '+672',
        country: 'Norfolk Island',
        isoCode: 'nf',
    },
    {
        flagIcon: <Flags.NorthKorea style={style} />,
        countryCode: '+850',
        country: 'North Korea',
        isoCode: 'kp',
    },
    {
        flagIcon: <Flags.NorthernMarianasIslands style={style} />,
        countryCode: '+1',
        country: 'Northern Mariana Islands',
        isoCode: 'mp',
    },
    {
        flagIcon: <Flags.Norway style={style} />,
        countryCode: '+47',
        country: 'Norway',
        isoCode: 'no',
    },
    {
        flagIcon: <Flags.Oman style={style} />,
        countryCode: '+968',
        country: 'Oman',
        isoCode: 'om',
    },
    {
        flagIcon: <Flags.Pakistan style={style} />,
        countryCode: '+92',
        country: 'Pakistan',
        isoCode: 'pk',
    },
    {
        flagIcon: <Flags.Palau style={style} />,
        countryCode: '+680',
        country: 'Palau',
        isoCode: 'pw',
    },
    {
        flagIcon: <Flags.Palestine style={style} />,
        countryCode: '+970',
        country: 'Palestine',
        isoCode: 'ps',
    },
    {
        flagIcon: <Flags.Panama style={style} />,
        countryCode: '+507',
        country: 'Panama',
        isoCode: 'pa',
    },
    {
        flagIcon: <Flags.PapuaNewGuinea style={style} />,
        countryCode: '+675',
        country: 'Papua New Guinea',
        isoCode: 'pg',
    },
    {
        flagIcon: <Flags.Paraguay style={style} />,
        countryCode: '+595',
        country: 'Paraguay',
        isoCode: 'py',
    },
    {
        flagIcon: <Flags.Peru style={style} />,
        countryCode: '+51',
        country: 'Peru',
        isoCode: 'pe',
    },
    {
        flagIcon: <Flags.Philippines style={style} />,
        countryCode: '+63',
        country: 'Philippines',
        isoCode: 'ph',
    },
    {
        flagIcon: <Flags.Poland style={style} />,
        countryCode: '+48',
        country: 'Poland',
        isoCode: 'pl',
    },
    {
        flagIcon: <Flags.Portugal style={style} />,
        countryCode: '+351',
        country: 'Portugal',
        isoCode: 'pt',
    },
    {
        flagIcon: <Flags.PuertoRico style={style} />,
        countryCode: '+1',
        country: 'Puerto Rico',
        isoCode: 'pr',
    },
    {
        flagIcon: <Flags.Qatar style={style} />,
        countryCode: '+974',
        country: 'Qatar',
        isoCode: 'qa',
    },
    {
        flagIcon: <Flags.Reunion style={style} />,
        countryCode: '+262',
        country: 'Réunion',
        isoCode: 're',
    },
    {
        flagIcon: <Flags.Romania style={style} />,
        countryCode: '+40',
        country: 'Romania',
        isoCode: 'ro',
    },
    {
        flagIcon: <Flags.Russia style={style} />,
        countryCode: '+7',
        country: 'Russia',
        isoCode: 'ru',
    },
    {
        flagIcon: <Flags.Rwanda style={style} />,
        countryCode: '+250',
        country: 'Rwanda',
        isoCode: 'rw',
    },
    {
        flagIcon: <Flags.SaintBarthelemy style={style} />,
        countryCode: '+590',
        country: 'Saint Barthélemy',
        isoCode: 'bl',
    },
    {
        flagIcon: <Flags.SaintHelena style={style} />,
        countryCode: '+290',
        country: 'Saint Helena',
        isoCode: 'sh',
    },
    {
        flagIcon: <Flags.SaintKittsAndNevis style={style} />,
        countryCode: '+1',
        country: 'Saint Kitts and Nevis',
        isoCode: 'kn',
    },
    {
        flagIcon: <Flags.SaintLucia style={style} />,
        countryCode: '+1',
        country: 'Saint Lucia',
        isoCode: 'lc',
    },
    {
        flagIcon: <Flags.SaintMartin style={style} />,
        countryCode: '+590',
        country: 'Saint Martin',
        isoCode: 'mf',
    },
    {
        flagIcon: <Flags.SaintPierreAndMiquelon style={style} />,
        countryCode: '+508',
        country: 'Saint Pierre and Miquelon',
        isoCode: 'pm',
    },
    {
        flagIcon: <Flags.SaintVincentAndTheGrenadines style={style} />,
        countryCode: '+1',
        country: 'Saint Vincent and the Grenadines',
        isoCode: 'vc',
    },
    {
        flagIcon: <Flags.Samoa style={style} />,
        countryCode: '+685',
        country: 'Samoa',
        isoCode: 'ws',
    },
    {
        flagIcon: <Flags.SanMarino style={style} />,
        countryCode: '+378',
        country: 'San Marino',
        isoCode: 'sm',
    },
    {
        flagIcon: <Flags.SaoTomeAndPrince style={style} />,
        countryCode: '+239',
        country: 'São Tomé and Príncipe',
        isoCode: 'st',
    },
    {
        flagIcon: <Flags.SaudiArabia style={style} />,
        countryCode: '+966',
        country: 'Saudi Arabia',
        isoCode: 'sa',
    },
    {
        flagIcon: <Flags.Senegal style={style} />,
        countryCode: '+221',
        country: 'Senegal',
        isoCode: 'sn',
    },
    {
        flagIcon: <Flags.Serbia style={style} />,
        countryCode: '+381',
        country: 'Serbia',
        isoCode: 'rs',
    },
    {
        flagIcon: <Flags.Seychelles style={style} />,
        countryCode: '+248',
        country: 'Seychelles',
        isoCode: 'sc',
    },
    {
        flagIcon: <Flags.SierraLeone style={style} />,
        countryCode: '+232',
        country: 'Sierra Leone',
        isoCode: 'sl',
    },
    {
        flagIcon: <Flags.Singapore style={style} />,
        countryCode: '+65',
        country: 'Singapore',
        isoCode: 'sg',
    },
    {
        flagIcon: <Flags.SintMaarten style={style} />,
        countryCode: '+1',
        country: 'Sint Maarten',
        isoCode: 'sx',
    },
    {
        flagIcon: <Flags.Slovakia style={style} />,
        countryCode: '+421',
        country: 'Slovakia',
        isoCode: 'sk',
    },
    {
        flagIcon: <Flags.Slovenia style={style} />,
        countryCode: '+386',
        country: 'Slovenia',
        isoCode: 'si',
    },
    {
        flagIcon: <Flags.SolomonIslands style={style} />,
        countryCode: '+677',
        country: 'Solomon Islands',
        isoCode: 'sb',
    },
    {
        flagIcon: <Flags.Somalia style={style} />,
        countryCode: '+252',
        country: 'Somalia',
        isoCode: 'so',
    },
    {
        flagIcon: <Flags.SouthAfrica style={style} />,
        countryCode: '+27',
        country: 'South Africa',
        isoCode: 'za',
    },
    {
        flagIcon: <Flags.SouthKorea style={style} />,
        countryCode: '+82',
        country: 'South Korea',
        isoCode: 'kr',
    },
    {
        flagIcon: <Flags.SouthSudan style={style} />,
        countryCode: '+211',
        country: 'South Sudan',
        isoCode: 'ss',
    },
    {
        flagIcon: <Flags.Spain style={style} />,
        countryCode: '+34',
        country: 'Spain',
        isoCode: 'es',
    },
    {
        flagIcon: <Flags.SriLanka style={style} />,
        countryCode: '+94',
        country: 'Sri Lanka',
        isoCode: 'lk',
    },
    {
        flagIcon: <Flags.Sudan style={style} />,
        countryCode: '+249',
        country: 'Sudan',
        isoCode: 'sd',
    },
    {
        flagIcon: <Flags.Suriname style={style} />,
        countryCode: '+597',
        country: 'Suriname',
        isoCode: 'sr',
    },
    {
        flagIcon: <Flags.SvalbardAndJanMayen style={style} />,
        countryCode: '+47',
        country: 'Svalbard and Jan Mayen',
        isoCode: 'sj',
    },
    {
        flagIcon: <Flags.Swaziland style={style} />,
        countryCode: '+268',
        country: 'Swaziland',
        isoCode: 'sz',
    },
    {
        flagIcon: <Flags.Sweden style={style} />,
        countryCode: '+46',
        country: 'Sweden',
        isoCode: 'se',
    },
    {
        flagIcon: <Flags.Switzerland style={style} />,
        countryCode: '+41',
        country: 'Switzerland',
        isoCode: 'ch',
    },
    {
        flagIcon: <Flags.Syria style={style} />,
        countryCode: '+963',
        country: 'Syria',
        isoCode: 'sy',
    },
    {
        flagIcon: <Flags.Taiwan style={style} />,
        countryCode: '+886',
        country: 'Taiwan',
        isoCode: 'tw',
    },
    {
        flagIcon: <Flags.Tajikistan style={style} />,
        countryCode: '+992',
        country: 'Tajikistan',
        isoCode: 'tj',
    },
    {
        flagIcon: <Flags.Tanzania style={style} />,
        countryCode: '+255',
        country: 'Tanzania',
        isoCode: 'tz',
    },
    {
        flagIcon: <Flags.Thailand style={style} />,
        countryCode: '+66',
        country: 'Thailand',
        isoCode: 'th',
    },
    {
        flagIcon: <Flags.TimorLeste style={style} />,
        countryCode: '+670',
        country: 'Timor-Leste',
        isoCode: 'tl',
    },
    {
        flagIcon: <Flags.Togo style={style} />,
        countryCode: '+228',
        country: 'Togo',
        isoCode: 'tg',
    },
    {
        flagIcon: <Flags.Tokelau style={style} />,
        countryCode: '+690',
        country: 'Tokelau',
        isoCode: 'tk',
    },
    {
        flagIcon: <Flags.Tonga style={style} />,
        countryCode: '+676',
        country: 'Tonga',
        isoCode: 'to',
    },
    {
        flagIcon: <Flags.TrinidadAndTobago style={style} />,
        countryCode: '+1',
        country: 'Trinidad and Tobago',
        isoCode: 'tt',
    },
    {
        flagIcon: <Flags.Tunisia style={style} />,
        countryCode: '+216',
        country: 'Tunisia',
        isoCode: 'tn',
    },
    {
        flagIcon: <Flags.Turkey style={style} />,
        countryCode: '+90',
        country: 'Turkey',
        isoCode: 'tr',
    },
    {
        flagIcon: <Flags.Turkmenistan style={style} />,
        countryCode: '+993',
        country: 'Turkmenistan',
        isoCode: 'tm',
    },
    {
        flagIcon: <Flags.TurksAndCaicos style={style} />,
        countryCode: '+1',
        country: 'Turks and Caicos Islands',
        isoCode: 'tc',
    },
    {
        flagIcon: <Flags.Tuvalu style={style} />,
        countryCode: '+688',
        country: 'Tuvalu',
        isoCode: 'tv',
    },
    {
        flagIcon: <Flags.UsVirginIslands style={style} />,
        countryCode: '+1',
        country: 'U.S Virgin Islands',
        isoCode: 'vi',
    },
    {
        flagIcon: <Flags.Uganda style={style} />,
        countryCode: '+256',
        country: 'Uganda',
        isoCode: 'ug',
    },
    {
        flagIcon: <Flags.Ukraine style={style} />,
        countryCode: '+380',
        country: 'Ukraine',
        isoCode: 'ua',
    },
    {
        flagIcon: <Flags.UnitedArabEmirates style={style} />,
        countryCode: '+971',
        country: 'United Arab Emirates',
        isoCode: 'ae',
    },
    {
        flagIcon: <Flags.UnitedKingdom style={style} />,
        countryCode: '+44',
        country: 'United Kingdom',
        isoCode: 'gb',
    },
    {
        flagIcon: <Flags.UnitedStates style={style} />,
        countryCode: '+1',
        country: 'United States',
        isoCode: 'us',
    },
    {
        flagIcon: <Flags.Uruguay style={style} />,
        countryCode: '+598',
        country: 'Uruguay',
        isoCode: 'uy',
    },
    {
        flagIcon: <Flags.Uzbekistan style={style} />,
        countryCode: '+998',
        country: 'Uzbekistan',
        isoCode: 'uz',
    },
    {
        flagIcon: <Flags.Vanuatu style={style} />,
        countryCode: '+678',
        country: 'Vanuatu',
        isoCode: 'vu',
    },
    {
        flagIcon: <Flags.VaticanCity style={style} />,
        countryCode: '+379',
        country: 'Vatican City',
        isoCode: 'va',
    },
    {
        flagIcon: <Flags.Venezuela style={style} />,
        countryCode: '+58',
        country: 'Venezuela',
        isoCode: 've',
    },
    {
        flagIcon: <Flags.Vietnam style={style} />,
        countryCode: '+84',
        country: 'Vietnam',
        isoCode: 'vn',
    },
    {
        flagIcon: <Flags.WallisAndFutuna style={style} />,
        countryCode: '+681',
        country: 'Wallis and Futuna',
        isoCode: 'wf',
    },
    {
        flagIcon: <Flags.Yemen style={style} />,
        countryCode: '+967',
        country: 'Yemen',
        isoCode: 'ye',
    },
    {
        flagIcon: <Flags.Zambia style={style} />,
        countryCode: '+260',
        country: 'Zambia',
        isoCode: 'zm',
    },
    {
        flagIcon: <Flags.Zimbabwe style={style} />,
        countryCode: '+263',
        country: 'Zimbabwe',
        isoCode: 'zw',
    },
];
